MODEL:
  model_name: EGN.EGN
  mdim: 1536
  extra_preprocess:
  - script: build_exemplar.py
    args:
      model_name: ~
      distance_metric: l1
      external_meta_dir: ~
  adapter: egn
DATA:
  dataset_name: EGNDataset
