GENERAL:
  use_amp: false
MODEL:
  model_name: stpath.STPathModule
  fine_tune: false
  skip_train: true
  adapter: contrastive
  gene_voc_path: STPath/utils_data/symbol2ensembl.json
  model_weight_path: weight/stfm.pth
  device: cpu
DATA:
  dataset_name: STPathDataset
  model_name: gigapath
  load_level: slide
